const products = [ 
    {
        id: 1,
        title: 'Maceta de Cemento',
        description: 'Pequeña vasija exagonal de cemento para adornos',
        price: 100.00,
        picture: "../img/miniMaceta1.jpg",
        category: "maceta",
        stock: 10,
        offer: 20,
    },
    {
        id: 2,
        title: 'Maceta de Cemento',
        description: 'Macetas cilindricas de diferentes colores',
        price: 200.00,
        picture: "../img/miniMaceta2.jpg",
        category: "maceta",
        stock: 10,
    },
    {
        id: 3,
        title: 'Maceta de Cemento',
        description: 'Pequeña vasija exagonal de cemento para adornos con planta includida',
        price: 300.00,
        picture: "../img/miniMaceta3.jpg",
        category: "maceta",
        stock: 10,
    },
    {
        id: 4,
        title: 'Velas Corazón',
        description: 'Adornos para el hogar',
        price: 100.00,
        picture: "../img/velas1.jpg",
        category: "velas",
        stock: 10,
    },
    {
        id: 5,
        title: 'Velas Corazón Cilindricas',
        description: 'Adornos para el hogar',
        price: 200.00,
        picture: "../img/velas2.jpg",
        category: "velas",
        stock: 10,
        offer: 20,
    },
    {
        id: 6,
        title: 'Velas Buho',
        description: 'Adornos para el hogar',
        price: 300.00,
        picture: "../img/velas3.jpg",
        category: "velas",
        stock: 10,
    },

];

export default products;